### ISSUE TITLE
`DataFrame(read_from_sas)` method that converts data loaded with `SASLib.read`

### ISSUE THREAD

**Issue by xiaodaigh** [tk3369/SASLib.jl#18]
Currently conversion to DataFrame requires `DataFrame(read_from_sas[:data])`. Overload the `DataFrame` method so that `DataFrame(read_from_sas)` automatically converts feels more Julian.

Also can default to convert in the same column order e.g. define a new Type that is `<: Dict{Symbol,Any}` and call it the `SASInput` or something so it dispatch on the following

`DataFrame(x::SASInput, colstable = true) = colstable ? DataFrame((c => x[:data][c]) for c in x[:column_symbols])...) : DataFrame(x[:data]);`

**Comment by tk3369** [comment]
I think integration with StatFiles.jl as proposed by @davidanthoff makes more sense.  See comments from #2.

**Comment by davidanthoff** [comment]
Yeah, I'm really impressed by the work in this repo, and essentially plan to switch StatFiles.jl over to use this package here once things are stable/settled down a bit. At that point ``DataFrame(load("myfile.sas7bdat")`` will just work, and the column order will be preserved. And of course it will not just work with ``DataFrame``, but pretty much anything else (JuliaDB etc.).

**Comment by tk3369** [comment]
@xiaodaigh The latest version makes the conversion to `DataFrame` a lot easier by using a standard two-argument constructor.  Column orders are also preserved.  I don't want to build yet another package dependency just for this so I'll leave it this way. 

Closing this issue.
