### ISSUE TITLE
Support 32-bit environment(?)

### ISSUE THREAD

**Issue by tk3369** [tk3369/SASLib.jl#21]
The current code uses a lot of Int64 types and that may be unnecessary and I'm unsure if that would work well in a 32-bit environment.  Not sure if it's worth the effort, however, since the world is migrating to 64-bit anyways... Logging an issue just so I don't forget.

**Comment by davidanthoff** [comment]
Easiest way to test that is to enable appveyor, that way you can run tests on a 32 bit system.

**Comment by tk3369** [comment]
Don't think it's worth working on this anymore since 64-bit is the norm.  
Closing issue.
