### ISSUE TITLE
String casing for symbols

### ISSUE THREAD

**Issue by tbeason** [tk3369/SASLib.jl#22]
As it currently stands, casing must match exactly when using `include_columns`. It will not always be the case that the user knows ahead of time how the column symbols look inside the file they are trying to load. I'm wondering how possible it is to be a bit more flexible on this front. For example, if file symbols are in all lower case, but I provide all upper case to `include_columns`, things will fail right now, but I'm wondering if that necessarily is the only possible way to handle this. 

As an alternative, perhaps there could be a function that just returns the column names in the file without loading the entire dataset, that would be another option.

If I remember correctly, SAS is agnostic about casing as well, so I don't see an issue. 

Just a suggestion.

**Comment by xiaodaigh** [comment]
yep sas doesnt care about casing for variable names

**Comment by tk3369** [comment]
Good suggestion

**Comment by davidanthoff** [comment]
I have to admit that I'm not a fan of this. Pretty much everything throughout julia is case-sensitive, so I think it would make sense to follow that pattern here.

**Comment by tk3369** [comment]
I hold a different, though not very strong, opinion.  This change is done for usability reason and only used for selecting columns (kinda like SQL is case insensitive as well).
