### ISSUE TITLE
Inconsistent naming of `:nrows` and `.row_count`

### ISSUE THREAD

**Issue by xiaodaigh** [tk3369/SASLib.jl#33]
When I try to read a file incrementally I wanted to looked at the number of rows and then decide how many to read in.

I can open a handle
```julia
handler = SASLib.open("data.sas7bdat")
```
and I was expecting one of the below to work

```julia
size(handler)
nrow(handler)
handler.nrows
handler[:nrows]
```

but the name is actually

```julia
handler.row_count
```
which seems inconsistent with how these things are named elsewhere, namely `:nrows`

**Comment by tk3369** [comment]
The `Handler` object was never meant to be accessed directly.  The proposed `Metadata` structure should make it more user friendly.  See sample usage of the `metadata` function in [Object Design for Metadata and Results](../wiki/Object+Design+for+Metadata+and+Results)

**Comment by tk3369** [comment]
Also see #29

**Comment by tk3369** [comment]
PR #36 will address this issue.  Closing.
