### ISSUE TITLE
handler.compression now returns a number

### ISSUE THREAD

**Issue by xiaodaigh** [tk3369/SASLib.jl#38]
```julia
using SASLib
a = SASLib.open("d:/hi.sas7bdat")
a.compression # return 0x02
```

And there isn't documentation on what the codes mean yet. Also compression isn't printed in the Handler output now.

**Comment by tk3369** [comment]
See `metadata` function from PR #36

**Comment by tk3369** [comment]
Merged.  See `master` branch.  I'll tag it soon.
