### ISSUE TITLE
Minor: auto-complete filename

### ISSUE THREAD

**Issue by tbeason** [tk3369/SASLib.jl#39]
If the package only supports `*.sas7bdat` file extensions, perhaps it would be convenient to just auto-complete this for the user (why is it so long in the first place!!?). I could probably get around to doing this when I procrastinate on something in the future if nobody has done it by then. Would use something like `splitext`.

Could probably also implement some input checking on the filename at the same time.

**Comment by tk3369** [comment]
What do you mean by auto-complete?  Not having to pass filename extension? I'm wondering why you want to do that.  I have just never seen any API doing that before...

**Comment by tbeason** [comment]
Yes. There is no ambiguity since the package only works for one type of file. Stata and SAS do this, again probably because they only work with a limited set of file types.
