### ISSUE TITLE
String columns need to be more space-efficient

### ISSUE THREAD

**Issue by tk3369** [tk3369/SASLib.jl#4]
String values are transcoded from the underlying byte stream and if the same string appears multiple times in the same column then it's repeated and consuming more memory.  Consider using 
[CategoricalArrays](https://github.com/JuliaData/CategoricalArrays.jl)?

**Comment by davidanthoff** [comment]
Another option is https://github.com/JuliaComputing/PooledArrays.jl. I think if you don't need support for the whole CategoricalValue machinery (i.e. factors) then it might be a simpler story. I also think there is less churn in that package right now.

**Comment by tk3369** [comment]
Come to think of it, we can't really assume anything.  What if the column has unique data?  Then there's no point in using either CategoricalArrays or PooledArrays.  Perhaps the more appropriate behavior is to let the user decide what kind of structure they need.  e.g.

```
julia> x = readsas("data_AHS2013/topical.sas7bdat")
Read data_AHS2013/topical.sas7bdat with size 84355 x 114 in 9.82767 seconds
Dict{Symbol,Any} with 16 entries:
  :filename             => "data_AHS2013/topical.sas7bdat"
  :page_length          => 16384
  :file_encoding        => "ISO-8859-1"
  :system_endianness    => :LittleEndian
  :ncols                => 114
  :column_types         => Type[Union{AbstractString, Missings.Missing}, Union{AbstractString, Missings.Missing}, Union{AbstractString, Missings.Missi…
  :data                 => Dict{Any,Any}(Pair{Any,Any}(:PTDISRAIL, Union{AbstractString, Missings.Missing}["B", "B", "B", "B", "B", "B", "B", "B", "B"…
  :perf_type_conversion => 0.0228557
  :page_count           => 824
  :column_names         => String["CONTROL", "EABAN", "EBARCL", "EJUNK", "EAGE", "DPALTCOM", "DPBNREAD", "DPDRFOOD", "CEFCLOSKNIT", "CEFDISRSPCT"  …  …
  :column_symbols       => Symbol[:CONTROL, :EABAN, :EBARCL, :EJUNK, :EAGE, :DPALTCOM, :DPBNREAD, :DPDRFOOD, :CEFCLOSKNIT, :CEFDISRSPCT  …  :DPGENERT,…
  :column_lengths       => [12, 1, 1, 1, 1, 1, 1, 1, 1, 1  …  1, 1, 1, 1, 1, 1, 1, 1, 8, 8]
  :file_endianness      => :LittleEndian
  :nrows                => 84355
  :perf_read_data       => 8.35592
  :column_offsets       => [64, 76, 77, 78, 79, 80, 81, 82, 83, 84  …  197, 198, 199, 200, 201, 202, 203, 204, 48, 56]

julia> Base.summarysize(x[:data][:WFPROP])
1434035

julia> size(x[:data][:WFPROP])
(84355,)

julia> unique(x[:data][:WFPROP])
5-element Array{String,1}:
 "B"
 "2"
 "1"
 "D"
 "R"

julia> x[:data][:WFPROP] = PooledArray(x[:data][:WFPROP]);

julia> size(x[:data][:WFPROP])
(84355,)

julia> unique(x[:data][:WFPROP])
5-element Array{String,1}:
 "B"
 "2"
 "1"
 "D"
 "R"

julia> Base.summarysize(x[:data][:WFPROP])
84456

julia> 1 - 84456 / 1434035
0.9411060399502105
```

**Comment by tk3369** [comment]
The only issue is that more memory is consumed since the same strings are repeated many times during read operation.   Another option is to give user a keyword argument to pass in a constructor that creates an array-like object that supports subscripting, as that's all the reader needs to fill in the blanks. Like this:

```
x = readsas("data_AHS2013/topical.sas7bdat", 
            column_array_types=Dict(:WFPROP => (ar) -> PooledArray(ar, Int8))
```

**Comment by davidanthoff** [comment]
I would take a look at how https://github.com/JuliaComputing/TextParse.jl handles this. The [documentation](https://juliacomputing.com/TextParse.jl/latest/) describes the strategy there, short version is that it starts out with a ``PooledArray``, but then switches over to a normal ``Array`` if a certain threshold of unique elements is hit. It also is very good about avoiding ``String`` allocations altogether when possible (and instead reusing already instantiated ``String``s).

**Comment by tk3369** [comment]
I would imagine that string data are usually repeated and id-type string columns are probably less common.  It's a fair assumption then that PooledArray would work well in most cases at least for larger data sets.  The bumping strategy sounds good and should be fairly easy to implement.  Thanks for your suggestion.

**Comment by tk3369** [comment]
I have learned that PooledArray becomes very slow when there are many unique values.  With the SAS reader, I'm doing `setindex!` for every row and the sorting mechanism kills performance.  Looks like PooledArray's pending [Dict Pool PR](https://github.com/JuliaComputing/PooledArrays.jl/pull/5) could solve my problem.  

In my test scenario, out of a 5000 element array with 2000 unique values:
- Regular array performs all assignments in 156 μs
- Pooled array (master) took 402 ms (!)
- Pooled array (dict pool) took 940 μs 
- Categorical array took 967 μs

**Comment by davidanthoff** [comment]
I think TextParse switches over to a regular array if more than 5% of the values are unique, right? So 2000 out of 5000 is probably just clearly not a case for a pooled storage?

**Comment by tk3369** [comment]
That's right. The issue is that none of the pool structure are very performant, probably due to the nature of maintaining the pool. Even Dict Pool is 4-5x slower than a regular array.  I could make it switch over to a regular array but I would be making an assumption that the user wants to save time than space.  

Perhaps the best solution is to do this switch-over logic + a user override so the flexibility isn't lost.  My other concern is about building another dependency to another package.  It may be better for the user of the API to decide what kind of array to use so SASLib stays lean.

DictPool
```
julia> @benchmark readsas("data_AHS2013/homimp.sas7bdat", include_columns=[:CONTROL], verbose_level=0)
BenchmarkTools.Trial: 
  memory estimate:  21.23 MiB
  allocs estimate:  299778
  --------------
  minimum time:     58.880 ms (0.00% GC)
  median time:      66.688 ms (10.16% GC)
  mean time:        67.301 ms (9.76% GC)
  maximum time:     78.575 ms (9.17% GC)
  --------------
  samples:          75
  evals/sample:     1
```

Regular array
```
julia> @benchmark readsas("data_AHS2013/homimp.sas7bdat", include_columns=[:CONTROL], verbose_level=0)
BenchmarkTools.Trial: 
  memory estimate:  14.92 MiB
  allocs estimate:  207718
  --------------
  minimum time:     13.338 ms (0.00% GC)
  median time:      19.715 ms (27.10% GC)
  mean time:        20.114 ms (20.62% GC)
  maximum time:     61.425 ms (27.85% GC)
  --------------
  samples:          249
  evals/sample:     1
```

**Comment by davidanthoff** [comment]
I like the idea to use the same heuristic as TextParse.jl does, but with an option to override. I hear you about dependencies, but just as one datapoint, I've had a dependency on TextParse.jl for a very long time and it seems very stable/reliable, and I would assume the same is true for PooledArray. Plus, it was mostly created by Jeff (one of the co-creators of julia), so it is almost certainly of high quality.

**Comment by tk3369** [comment]
I generally don't like reinventing wheels but in this case I want better performance and so I created a new ObjectPool within the package.  

The heuristic is there now but I think we may want to consider adding more knobs in the future... right now the logic is pretty much hard-coded (from commit 598c07):
```
            if isa(ar, ObjectPool) &&
                    handler.row_count > 10000 &&
                    handler.current_row_in_file_index > 1 &&
                    handler.current_row_in_file_index % 200 == 0 &&
                    ar.uniqueitemscount / ar.itemscount > 0.05
                println2(handler, "Bumping column $(name) to regular array due to too many unique items $(ar.uniqueitemscount) out of $( ar.itemscount)")
```
