### ISSUE TITLE
incorrect encoding for east asia characters 

### ISSUE THREAD

**Issue by testercwt** [tk3369/SASLib.jl#69]
The constants.jl contains  incorrect information for east asia character
----
here is the correct (east asia character)  encodings as below

    118 => "CP950",
    119 => "EUC-TW",
    123 => "BIG5-HKSCS",
    125 => "GB18030",
    126 => "CP936",
    134 => "EUC-JP",
    136 => "CP932",
    138 => "CP932",
    140 => "EUC-KR",
    141 => "CP949"
----
ref
https://support.sas.com/documentation/onlinedoc/dfdmstudio/2.6/dmpdmsug/Content/dfU_Encodings_SAS.html

**Comment by tk3369** [comment]
Thanks.  Do you mind submitting a PR? Do you have any test files with these encodings?

**Comment by testercwt** [comment]
fixed
