### ISSUE TITLE
Backport of PR

### ISSUE THREAD

**Issue by cwiese** [tk3369/SASLib.jl#78]
Tom   - we are in production on SASLib v1.2.0.    We can not update the dependent packages for 1.3.1 without huge risk.   

I created a branch from v1.2.0 - but it will not let me create a PR unless I compare with Master (cwiese:caw/object_pool_backport).

How can we patch 1.2.0 with these changes?   Chuck

**Comment by cwiese** [comment]
@tk3369

**Comment by tk3369** [comment]
Hey, I've just tagged a backport release. Have fun!

https://github.com/tk3369/SASLib.jl/releases/tag/v1.2.2
