### ISSUE TITLE
Speed issues with Missing on julia 0.6

### ISSUE THREAD

**Issue by davidanthoff** [tk3369/SASLib.jl#9]
I saw that you just started using ``Vector{Union{Missing,T}}``. If you want to create something fast on julia 0.6, I think you'll have to stay away from that for now because all the things that will make that fast are not in julia 0.6, and will only come in julia 0.7.

I think there are various alternatives on julia 0.6:
- You can use [DataArrays.jl](https://github.com/JuliaStats/DataArrays.jl). That will be a bit better, but probably still not ideal because you might run into type stability issues. Another issue might be that lots of folks will not be able to get the version that supports ``Missing`` because there are probably dozens of packages that need updating and will hold back users from getting that version.
- You can use ``DataValueArray`` from [DataValues.jl](https://github.com/davidanthoff/DataValues.jl). That should give you the best performance on julia 0.6. [TextParse.jl](https://github.com/JuliaComputing/TextParse.jl), [ReadStat.jl](https://github.com/davidanthoff/ReadStat.jl) and soon [ExcelReaders.jl](https://github.com/davidanthoff/ExcelReaders.jl) us that right now (and also [JuliaDB.jl](https://github.com/JuliaComputing/JuliaDB.jl)). It is not the official julia missing data story, but on the flipside it works well, and is fast on julia 0.6, is stable (i.e. no churn in the package you have to track) and might be a good bridge tech until the whole ``Missing`` story is sorted out.
- You could just return a ``Tuple{Vector{T},Vector{Bool}}`` with a missing mask... Not elegant, but if you don't want to make a hard choice at this point, that would also be an option. I think this comes down a bit whether you expect end-users to interact much with SASLib.jl, or whether you think most end-users might interact with it more via a package like [StatFiles.jl](https://github.com/davidanthoff/StatFiles.jl), which could hide all of these details from users.

**Comment by tk3369** [comment]
David, working hard before year end? :-)

I was indeed a bit uneasy when I put Missings package into use, knowing that some big changes are coming down the pipe.  I wanted to fix the load issue for Date/DateTime columns but I couldn't think of any other magic value to use.   

Thanks very much about your suggestions above. I do want to make it fast but given 0.7 (or is it 1.0) is right around the corner, wouldn't it be better to wait and refactor the code then?   I'm new to Julia and not even sure if there's going to be an official way to deal with missing values.  Any additional thoughts are welcome.

**Comment by davidanthoff** [comment]
I guess it all depends on what "right around the corner" means ;) If history is any guide, I'm pretty sure that a 0.7 final is still a couple of months away.

**Comment by tk3369** [comment]
Not worry about Julia 0.6 anymore :-) 
Closing issue.
